import { readFileSync, existsSync, statSync } from 'fs';
import { execSync } from 'child_process';

const MAX_FILE_SIZE = 200_000; // Don't analyze files larger than 200KB

const CODE_EXTENSIONS = new Set([
  '.js', '.ts', '.jsx', '.tsx', '.py', '.go', '.rs', '.java', '.cs',
  '.cpp', '.c', '.h', '.rb', '.php', '.swift', '.kt', '.scala',
  '.vue', '.svelte', '.css', '.scss', '.html', '.sh', '.bash',
  '.json', '.yaml', '.yml', '.toml', '.md',
]);

// Patterns that appear disproportionately in AI-generated code
const AI_CODE_PATTERNS = [
  // Verbose inline comments explaining obvious things
  { regex: /\/\/\s*(This|The|We|Here|Note:|TODO:|FIXME:|Helper|Utility|Main|Core)/gi, name: 'verbose-comments', weight: 0.1 },
  // "Generated by" markers
  { regex: /generated by|auto-generated|this file was/gi, name: 'generation-marker', weight: 0.8 },
  // Co-authored-by Claude/Copilot in files (not just git)
  { regex: /co-authored-by.*(claude|copilot|gpt|ai)/gi, name: 'coauthor-marker', weight: 0.9 },
  // Overly descriptive function/variable names
  { regex: /\b(handleError|processData|calculateResult|validateInput|formatOutput|parseResponse)\b/g, name: 'generic-names', weight: 0.05 },
  // TODO comments AI commonly generates
  { regex: /\/\/\s*TODO:\s*(implement|add|handle|check|validate|consider)/gi, name: 'ai-todo', weight: 0.1 },
  // Docstring patterns AI loves
  { regex: /\/\*\*[\s\S]{200,}\*\//g, name: 'verbose-docstring', weight: 0.15 },
  // Error message patterns AI uses
  { regex: /['"`](An error occurred|Something went wrong|Failed to|Unable to|Could not)\b/gi, name: 'generic-error-msg', weight: 0.08 },
  // Type assertion casts AI commonly produces
  { regex: /as\s+unknown\s+as\s+\w+|<any>/g, name: 'unsafe-cast', weight: 0.05 },
  // Console.log with descriptive messages (AI always explains its logs)
  { regex: /console\.(log|error|warn)\(['"`][A-Z][^'"`,]{10,}['"`]/g, name: 'descriptive-log', weight: 0.05 },
];

export function analyzeFileContent(filePath, extension) {
  if (!CODE_EXTENSIONS.has(extension)) return null;
  if (!existsSync(filePath)) return null;

  try {
    const stat = statSync(filePath);
    if (stat.size > MAX_FILE_SIZE || stat.size === 0) return null;

    const content = readFileSync(filePath, 'utf8');
    const lines = content.split('\n');

    return {
      lineCount: lines.length,
      ...computeMetrics(content, lines),
    };
  } catch {
    return null;
  }
}

function computeMetrics(content, lines) {
  let commentLines = 0;
  let blankLines = 0;
  let codeLines = 0;
  let totalLineLen = 0;
  let longLines = 0; // >120 chars (AI tends to write long lines)

  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed) {
      blankLines++;
    } else if (
      trimmed.startsWith('//') ||
      trimmed.startsWith('#') ||
      trimmed.startsWith('*') ||
      trimmed.startsWith('/*') ||
      trimmed.startsWith('"""') ||
      trimmed.startsWith("'''")
    ) {
      commentLines++;
    } else {
      codeLines++;
    }
    totalLineLen += line.length;
    if (line.length > 120) longLines++;
  }

  const totalNonBlank = commentLines + codeLines;
  const commentRatio = totalNonBlank > 0 ? commentLines / totalNonBlank : 0;
  const avgLineLen = lines.length > 0 ? totalLineLen / lines.length : 0;

  // Pattern matching
  const patternHits = [];
  let aiSignalScore = 0;

  for (const { regex, name, weight } of AI_CODE_PATTERNS) {
    const matches = [...content.matchAll(regex)];
    if (matches.length > 0) {
      patternHits.push({ pattern: name, count: matches.length });
      aiSignalScore += weight * Math.min(matches.length, 5);
    }
  }

  // High comment ratio is a signal (AI comments everything)
  if (commentRatio > 0.3) aiSignalScore += 0.1;
  if (commentRatio > 0.5) aiSignalScore += 0.2;

  return {
    commentLines,
    codeLines,
    blankLines,
    commentRatio: Math.round(commentRatio * 100) / 100,
    avgLineLength: Math.round(avgLineLen),
    longLines,
    aiPatternHits: patternHits,
    aiContentScore: Math.min(Math.round(aiSignalScore * 100) / 100, 1.0),
  };
}

/**
 * Analyze added lines in a git commit for AI code patterns.
 */
export function analyzeGitDiff(projectDir, commitHash) {
  try {
    const diff = execSync(`git show ${commitHash} --unified=0`, {
      cwd: projectDir,
      encoding: 'utf8',
      timeout: 5000,
      maxBuffer: 500_000,
    });

    const addedLines = diff.split('\n')
      .filter((l) => l.startsWith('+') && !l.startsWith('+++'))
      .map((l) => l.substring(1));

    return { addedLineCount: addedLines.length, ...computeMetrics(addedLines.join('\n'), addedLines) };
  } catch {
    return null;
  }
}
