import { execSync } from 'child_process';
import { existsSync } from 'fs';
import { join } from 'path';

// Patterns in commit messages that may indicate AI assistance
const AI_MESSAGE_PATTERNS = [
  /^(add|update|fix|refactor|implement|create|remove|improve|enhance)\s/i,
  /generated by/i,
  /co-authored-by.*claude/i,
  /co-authored-by.*copilot/i,
  /\[ai\]/i,
];

export function isGitRepo(dir) {
  return existsSync(join(dir, '.git'));
}

export function getRecentCommits(projectDir, sinceISO) {
  if (!isGitRepo(projectDir)) return [];

  try {
    // Get commit hashes + timestamps + subjects since tracking started
    const logOutput = execSync(
      `git log --format="%H|||%ai|||%s|||%an" --since="${sinceISO}" --no-merges`,
      { cwd: projectDir, encoding: 'utf8', timeout: 5000 }
    ).trim();

    if (!logOutput) return [];

    const commitLines = logOutput.split('\n').filter(Boolean);
    const commits = [];

    for (const line of commitLines) {
      const [hash, date, subject, author] = line.split('|||');
      if (!hash) continue;

      let insertions = 0;
      let deletions = 0;
      let filesChanged = 0;

      try {
        const stat = execSync(`git diff --shortstat ${hash}^..${hash} 2>/dev/null`, {
          cwd: projectDir,
          encoding: 'utf8',
          timeout: 3000,
        }).trim();

        const filesMatch = stat.match(/(\d+) file/);
        const insMatch = stat.match(/(\d+) insertion/);
        const delMatch = stat.match(/(\d+) deletion/);

        if (filesMatch) filesChanged = parseInt(filesMatch[1]);
        if (insMatch) insertions = parseInt(insMatch[1]);
        if (delMatch) deletions = parseInt(delMatch[1]);
      } catch {}

      const aiScore = scoreCommit({ subject, insertions, deletions, filesChanged });

      commits.push({
        hash: hash.trim(),
        time: date.trim(),
        message: subject.trim(),
        author: author.trim(),
        filesChanged,
        insertions,
        deletions,
        totalLines: insertions + deletions,
        aiScore,
        likelyAI: aiScore >= 0.5,
      });
    }

    return commits;
  } catch {
    return [];
  }
}

export function getGitConfig(projectDir) {
  if (!isGitRepo(projectDir)) return {};
  const cfg = {};
  try {
    cfg.userName = execSync('git config user.name', { cwd: projectDir, encoding: 'utf8' }).trim();
    cfg.userEmail = execSync('git config user.email', { cwd: projectDir, encoding: 'utf8' }).trim();
  } catch {}
  return cfg;
}

function scoreCommit({ subject, insertions, deletions, filesChanged }) {
  let score = 0;

  // Large commits are more likely AI-generated
  if (insertions > 200) score += 0.3;
  else if (insertions > 50) score += 0.15;

  // Many files changed at once suggests AI scaffolding
  if (filesChanged > 10) score += 0.25;
  else if (filesChanged > 5) score += 0.1;

  // Generic/formulaic commit messages
  for (const pattern of AI_MESSAGE_PATTERNS) {
    if (pattern.test(subject)) {
      score += 0.2;
      break;
    }
  }

  // Short, vague messages (AI often writes "Add X" without context)
  if (subject.split(' ').length <= 4) score += 0.1;

  return Math.min(score, 1.0);
}
